#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

indicate_regular_preinit() {
    echo "- regular preinit -"
}

boot_hook_add preinit_main indicate_regular_preinit

