(function(e){CanvasRenderingContext2D.prototype.JTopoRoundRect=function(d,c,a,h,f){"undefined"==typeof f&&(f=5);this.beginPath();this.moveTo(d+f,c);this.lineTo(d+a-f,c);this.quadraticCurveTo(d+a,c,d+a,c+f);this.lineTo(d+a,c+h-f);this.quadraticCurveTo(d+a,c+h,d+a-f,c+h);this.lineTo(d+f,c+h);this.quadraticCurveTo(d,c+h,d,c+h-f);this.lineTo(d,c+f);this.quadraticCurveTo(d,c,d+f,c);this.closePath()};JTopo={zIndex_Link:2,zIndex_Node:3};e.JTopo=JTopo})(window);
(function(e){e.util={isIE:!(!window.attachEvent||-1!==navigator.userAgent.indexOf("Opera")),getEventPosition:function(d){var c={},a;for(a in d)"returnValue"!=a&&"keyLocation"!=a&&(c[a]=d[a]);c.changedTouches?c.changedTouches[0].pageX?(c.pageX=c.changedTouches[0].pageX,c.pageY=c.changedTouches[0].pageY):(c.pageX=c.changedTouches[0].clientX+document.body.scrollLeft-document.body.clientLeft,c.pageY=c.changedTouches[0].clientY+document.body.scrollTop-document.body.clientTop):c.pageX||(c.pageX=c.clientX+
document.body.scrollLeft-document.body.clientLeft,c.pageY=c.clientY+document.body.scrollTop-document.body.clientTop);return c},getOffsetPosition:function(d){if(!d)return{left:0,top:0};var c=0,a=0;if("getBoundingClientRect"in document.documentElement){c=d.getBoundingClientRect();a=d.ownerDocument;d=a.body;var h=a.documentElement,f=h.clientLeft||d.clientLeft||0,a=c.top+(self.pageYOffset||h&&h.scrollTop||d.scrollTop)-(h.clientTop||d.clientTop||0),c=c.left+(self.pageXOffset||h&&h.scrollLeft||d.scrollLeft)-
f}else{do a+=d.offsetTop||0,c+=d.offsetLeft||0,d=d.offsetParent;while(d)}return{left:c,top:a}},clone:function(d){for(var c in d);return d}}})(JTopo);
(function(e){e.Stage=function(d){function c(a){a=e.util.getEventPosition(a);var g=e.util.getOffsetPosition(b.canvas);a.offsetLeft=a.pageX-g.left;a.offsetTop=a.pageY-g.top;a.x=a.offsetLeft;a.y=a.offsetTop;a.target=null;return a}function a(a){a=c(a);b.dispatchEventToScenes("click",a)}function h(a){a=c(a);b.dispatchEventToScenes("dbclick",a)}function f(a){a=c(a);b.dispatchEventToScenes("touchstart",a)}function g(a){a=c(a);b.dispatchEventToScenes("mousemove",a)}var b=this;this.initialize=function(b){e.util.isIE||
!window.addEventListener?(d.onclick=a,d.ondblclick=h,d.onmousemove=g):(d.addEventListener("click",a),d.addEventListener("dblclick",h),d.addEventListener("mousemove",g),d.addEventListener("touchstart",f));this.canvas=b;this.graphics=b.getContext("2d");this.childs=[];this.frames=24;this.needRepaint=!0};d&&this.initialize(d);this.dispatchEventToScenes=function(b,a){0!=this.frames&&(this.needRepaint=!0);this.childs.forEach(function(g){var c=g[b+"Handler"];if(null==c)throw Error("Function not found:"+
b+"Handler");c.call(g,a)})};this.add=function(b){for(var a=0;a<this.childs.length;a++)if(this.childs[a]==b)return;b.addTo(this);this.childs.push(b)};this.paint=function(){null!=this.canvas&&(this.graphics.save(),this.graphics.clearRect(0,0,this.canvas.width,this.canvas.height),this.childs.forEach(function(a){a.repaint(b.graphics)}),this.graphics.restore())};this.repaint=function(){0==this.frames||0>this.frames&&!1==this.needRepaint||(this.paint(),0>this.frames&&(this.needRepaint=!1))}}})(JTopo);
(function(e){e.Scene=function(d){var c=this;this.initialize=function(){this.elementType="scene";this.childs=[];this.zIndexMap={};this.zIndexArray=[];this.touchstartCallback=this.dbclickCallback=null};this.initialize();this.addTo=function(a){this.stage!==a&&null!=a&&(this.stage=a)};null!=d&&(d.add(this),this.addTo(d));this.paint=function(a){null!=this.stage&&(a.save(),a.restore(),a.save(),this.paintChilds(a),a.restore())};this.repaint=function(a){this.paint(a)};this.paintChilds=function(a){for(var c=
0;c<this.zIndexArray.length;c++)for(var d=this.zIndexMap[this.zIndexArray[c]],g=0;g<d.length;g++){var b=d[g];a.save();if(1==b.transformAble){var l=b.getCenterLocation();a.translate(l.x,l.y)}b.paint(a);a.restore()}};this.add=function(a){this.childs.push(a);null==this.zIndexMap[a.zIndex]&&(this.zIndexMap[a.zIndex]=[],this.zIndexArray.push(a.zIndex),this.zIndexArray.sort(function(a,c){return c-a}));this.zIndexMap[""+a.zIndex].push(a)};this.clear=function(){this.childs=[];this.zIndexArray=[];this.zIndexMap=
{}};this.getElementByXY=function(a,c){var d=null,g=this.zIndexMap[e.zIndex_Node];if(g&&0<g.length)for(var b=g.length-1;0<=b;b--){var l=g[b];(l instanceof e.Node||l instanceof e.ButtonNode)&&l.isInBound(a,c)&&(d=l)}return d};this.selectElement=function(a){var d=c.getElementByXY(a.x,a.y);null!=d&&(a.target=d);this.currentElement=d};this.toSceneEvent=function(a){a=e.util.clone(a);null!=this.currentElement&&(a.target=this.currentElement);a.scene=this;return a};this.clickHandler=function(a){if("function"==
typeof this.onclick)this.onclick();this.selectOperationNode(a);a=this.toSceneEvent(a);this.currentElement&&(a.target=this.currentElement,this.currentElement.clickHandler(a))};this.getEditNodeByXY=function(a,c){var d=null,g=this.zIndexMap[e.zIndex_Node];if(g&&0<g.length)for(var b=g.length-1;0<=b;b--){var l=g[b];l instanceof e.Node&&l.isInEditBound(a,c)&&(d=l)}return d};this.getOperationNodeByXY=function(a,c){var d=null,g=this.zIndexMap[e.zIndex_Node];if(g&&0<g.length)for(var b=g.length-1;0<=b;b--){var l=
g[b];l instanceof e.Node&&l.isInOperationBound(a,c)&&(d=l)}return d};this.selectEditNode=function(a){var c=this.getEditNodeByXY(a.x,a.y);null!=c&&(a.target=c);this.currentElement=c};this.selectOperationNode=function(a){var c=this.getOperationNodeByXY(a.x,a.y);null!=c&&(a.target=c);this.currentElement=c};this.dbclickHandler=function(a){this.selectEditNode(a);a={};this.currentElement&&(a.target=this.currentElement,a.pageX=this.currentElement.x+Math.floor(this.currentElement.textX),a.pageY=this.currentElement.y+
Math.floor(this.currentElement.textY),a.textWidth=this.currentElement.textRectWidth,a.textHeight=this.currentElement.textRectHeight,this.dbclickCallback(a))};this.touchstartHandler=function(a){this.selectEditNode(a);var c={};if(this.currentElement)c.target=this.currentElement,c.pageX=this.currentElement.x+Math.floor(this.currentElement.textX),c.pageY=this.currentElement.y+Math.floor(this.currentElement.textY),c.textWidth=this.currentElement.textRectWidth,c.textHeight=this.currentElement.textRectHeight,
this.touchstartCallback(c);else if(this.selectOperationNode(a),this.currentElement){if("function"==typeof this.onclick)this.onclick();c=this.toSceneEvent(a);this.currentElement&&(c.target=this.currentElement,this.currentElement.clickHandler(c))}};this.mousemoveHandler=function(a){a=this.toSceneEvent(a);var d=c.getElementByXY(a.x,a.y);if(null==d||d instanceof e.Node)d=c.getEditNodeByXY(a.x,a.y),null==d&&(d=c.getOperationNodeByXY(a.x,a.y));null!=d?(c.mouseOverElement&&c.mouseOverElement!==d&&(a.target=
d,c.mouseOverElement.mouseoutHandler(a,c)),c.mouseOverElement=d,0==d.isMouseOver&&(a.target=d,d.mouseoverHandler(a,c))):c.mouseOverElement?(a.target=d,c.mouseOverElement.mouseoutHandler(a,c),c.mouseOverElement=null):a.target=null};this.getCenterLocation=function(){return{x:c.stage.canvas.width/2,y:c.stage.canvas.height/2}};this.doLayout=function(a){a&&a(this,this.childs)};this.dbclick=function(a){null!=a&&(this.dbclickCallback=a)};this.tarchstart=function(a){null!=a&&(this.touchstartCallback=a)}}})(JTopo);
(function(e){function d(){this.initialize=function(){d.prototype.initialize.apply(this,arguments);this.elementType="interactiveElement";this.isMouseOver=!1};this.initialize();this.isInBound=function(c,a){return c>this.x&&c<this.x+this.width&&a>this.y&&a<this.y+this.height};this.clickHandler=function(c){};this.mouseoverHandler=function(c,a){this.isMouseOver=!0;a.stage.canvas.style.cursor="pointer"};this.mouseoutHandler=function(c,a){this.isMouseOver=!1;a.stage.canvas.style.cursor="default"}}d.prototype=
new function(){this.initialize=function(){this.elementType="displayElement";this.cy=this.cx=this.y=this.x=0;this.height=this.width=64;this.visible=!0;this.scaleY=this.scaleX=this.alpha=1;this.fillColor=this.borderColor=this.strokeColor="22,124,255";this.transformAble=!1;this.zIndex=0};this.initialize();this.setLocation=function(c,a){this.x=c;this.y=a};this.getCenterLocation=function(){return{x:this.x+this.width/2,y:this.y+this.height/2}};this.setSize=function(c,a){this.width=c;this.height=a};this.setBound=
function(c,a,d,e){this.setLocation(c,a);this.setSize(d,e)};this.getCx=function(){return this.x+this.width/2};this.getCy=function(){return this.y+this.height/2}};e.InteractiveElement=d})(JTopo);
(function(e){function d(a){this.wrapText=function(b,a,g,c){this.textRectHeight=4;if(null!=b&&""!=b){var d=288>a.measureText(b).width?!0:!1,e="",f=0,h=b.split(""),n="",k=0;d||(e=b.slice(b.length-5,b.length),f=a.measureText(e).width);for(b=0;b<h.length;b++){var d=n+h[b],t=a.measureText(d).width,p=a.measureText("田").width+2,k=k+a.measureText(h[b]).width;if(288<k)break;if(96<t)a.fillText(n,g,c),n=h[b],c+=p,this.textRectHeight+=13;else if(192<k&&t>96-f){n=n+"..."+e;break}else n=d}288>=k&&(96<k?(e=a.measureText(n).width,
a.fillText(n,g+(96-e)/2,c)):a.fillText(n,g,c),this.textRectHeight+=13)}};this.initialize=function(b){d.prototype.initialize.apply(this,arguments);this.zIndex=e.zIndex_Node;this.text=b;this.font="12px 微软雅黑, 宋体, Arial";this.fontColor="255,255,255";this.textOffsetY=this.textOffsetX=0;this.transformAble=!0;this.number=this.outLinks=this.inLinks=null;this.textY=this.textX=this.textRectWidth=this.textRectHeight=0;this.showOperation=!0;this.image};this.initialize(a);this.paint=function(b){if(this.image){b.save();
b.fillStyle="#009188";b.JTopoRoundRect(-this.width/2,-this.height/2,this.width,this.height,12);b.fill();b.restore();var a=b.globalAlpha;b.globalAlpha=this.alpha;b.drawImage(this.image,this.imgOffsetX,this.imgOffsetY,this.imgWidth,this.imgHeight,-this.imgScaleWidth/2,-this.imgScaleHeight/2,this.imgScaleWidth,this.imgScaleHeight);b.globalAlpha=a;this.paintText(b);this.paintNumber(b);this.paintOperation(b)}else{var g=this;f=new Image;f.src="../web-static/images/routerBg.png";f.onload=function(){g.image=
f;g.paintText(b);g.paintNumber(b);g.paintOperation(b)}}};this.paintOperation=function(b){this.showOperation&&(this.isMeshSta?b.drawImage(this.image,376,331,22,22,this.width/2-13,-this.height/2-6,22,22):b.drawImage(this.image,376,308,22,22,this.width/2-13,-this.height/2-6,22,22))};this.paintNumber=function(b){if(null!=this.number&&0!=this.number){var a=this.width/2-18,g=this.height/2-7;"99+"==this.number&&(a-=10,g+=0);b.beginPath();b.font=this.font;b.save();b.fillStyle="rgba(0, 176, 165, 1)";"99+"==
this.number?b.JTopoRoundRect(this.width/2-35,this.height/2-22,34,20,12):b.arc(this.width/2-11,this.height/2-12,10,0,2*Math.PI);b.fill();b.restore();b.fillStyle="rgba("+this.fontColor+","+this.alpha+")";b.fillText(this.number,a,g);b.closePath()}};this.paintText=function(b){var a=this.text;if(void 0!=a&&""!=a){b.beginPath();b.font=this.font;var g=b.measureText(a).width,c=b.measureText("田").width,g=this.getTextPosition(g,c);b.fillStyle="rgba("+this.fontColor+","+this.alpha+")";this.wrapText(a,b,g.x,
g.y);b.closePath()}};this.getTextPosition=function(b,a){var g={x:-(96<b?96:b)/2,y:this.height/2+a};null!=this.textOffsetX&&(g.x+=this.textOffsetX);null!=this.textOffsetY&&(g.y+=this.textOffsetY);return g};this.setImagePosition=function(b,a,g,c,d,e){this.imgOffsetX=b;this.imgOffsetY=a;this.imgWidth=g;this.imgHeight=c;this.imgScaleWidth=d||g;this.imgScaleHeight=e||c;if(void 0==f){var h=this;f=new Image;f.src="../web-static/images/routerBg.png";f.onload=function(){h.image=f}}else this.image=f};this.setWifiImagePosition=
function(b,a){this.wifiImgOffsetX=b;this.wifiImgOffsetY=a}}function c(){c.prototype.initialize.apply(this,arguments);this.mouseoverHandler=function(a,b){this.isMouseOver=!0;b.stage.canvas.style.cursor="pointer";if(!this.isInOperationBound(a.x,a.y)&&"function"==typeof this.onmouseover){var c={};c.x=this.x;c.y=this.y;c.textWidth=this.textRectWidth;c.textHeight=this.textRectHeight;this.onmouseover(c,this.text)}};this.mouseoutHandler=function(a,b){this.isMouseOver=!1;b.stage.canvas.style.cursor="default";
if(!this.isInOperationBound(a.x,a.y)&&"function"==typeof this.onmouseout)this.onmouseout()};this.clickHandler=function(a){if(this.isInOperationBound(a.x,a.y)&&(a={target:this},"function"==typeof this.onclick))this.onclick(a)};this.isInOperationBound=function(a,b){return a>this.x+this.width-14&&a<this.x+this.width+10&&b>this.y-10&&b<this.y+16?!0:!1};this.isInEditBound=function(a,b){var c=this.width>this.textRectWidth?0:(this.textRectWidth-this.width)/2;return a>this.x-c&&a<this.x+this.width+c&&b>this.y+
this.height+this.textOffsetY&&b<this.y+this.height+this.textRectHeight+this.textOffsetY?!0:!1}}function a(a){this.initialize();this.text=a;this.elementType="TextNode";this.paint=function(a){a.beginPath();a.font=this.font;this.width=a.measureText(this.text).width;this.height=a.measureText("田").width;a.strokeStyle="rgba("+this.fontColor+", "+this.alpha+")";a.fillStyle="rgba("+this.fontColor+", "+this.alpha+")";a.fillText(this.text,-this.width/2,this.height/2);a.closePath()}}function h(a){this.initialize=
function(a){h.prototype.initialize.apply(this,arguments);this.text=a;this.elementType="ButtonNode";this.fontColor="51, 51, 51";this.font="10px 微软雅黑, 宋体, Arial";this.backgroundColor="254, 235, 26";this.onclick=null};this.initialize(a);this.paint=function(a){a.beginPath();a.font=this.font;this.width=a.measureText(this.text).width+16;this.height=a.measureText("田").width+6;a.save();a.fillStyle="rgba("+this.backgroundColor+",1)";a.JTopoRoundRect(0,0,this.width,this.height,4);a.fill();a.restore();a.strokeStyle=
"rgba("+this.fontColor+", "+this.alpha+")";a.fillStyle="rgba("+this.fontColor+", "+this.alpha+")";a.fillText(this.text,8,this.height-4);a.closePath()};this.clickHandler=function(a){if("function"==typeof this.onclick)this.onclick(a)}}var f;d.prototype=new e.InteractiveElement;c.prototype=new d;a.prototype=new c;h.prototype=new d;e.Node=c;e.TextNode=a;e.ButtonNode=h})(JTopo);
(function(e){function d(a,c,f){this.initialize=function(a,b,c){d.prototype.initialize.apply(this,arguments);this.elementType="link";this.zIndex=e.zIndex_Link;0!=arguments.length&&(this.text=c,this.nodeA=a,this.nodeZ=b,this.nodeA&&null==this.nodeA.outLinks&&(this.nodeA.outLinks=[]),this.nodeA&&null==this.nodeA.inLinks&&(this.nodeA.inLinks=[]),this.nodeZ&&null==this.nodeZ.outLinks&&(this.nodeZ.outLinks=[]),this.nodeZ&&null==this.nodeZ.inLinks&&(this.nodeZ.inLinks=[]),null!=this.nodeA&&this.nodeA.outLinks.push(this),
null!=this.nodeZ&&this.nodeZ.outLinks.push(this),this.lineWidth=2,this.transformAble=!1,this.dashedPattern=null,this.strokeColor="255, 255, 255",this.bundleGap=12)};this.initialize(a,c,f);this.paintPath=function(a,b){a.beginPath();a.moveTo(b[0].x,b[0].y);for(var c=1;c<b.length;++c)a.lineTo(b[c].x,b[c].y);a.stroke();a.closePath()};this.paintWifiImage=function(a,b){b[b.length-1]&&this.nodeZ.image&&a.drawImage(this.nodeZ.image,this.nodeZ.wifiImgOffsetX,this.nodeZ.wifiImgOffsetY,20,20,b[b.length-1].x-
10,b[b.length-1].y-18,20,20)};this.paint=function(a){if(null!=this.nodeA&&null!=this.nodeZ){var b=this.getPath();a.strokeStyle="rgba("+this.strokeColor+","+this.alpha+")";a.lineWidth=this.lineWidth;this.paintPath(a,b);this.paintWifiImage(a,b)}}}function c(a,d,e){this.initialize=function(){this.roundLine=!1;c.prototype.initialize.apply(this,arguments)};this.initialize(a,d,e);this.getStartPosition=function(){var a={x:this.nodeA.getCx()};a.y=this.nodeA.y+this.nodeA.height+this.nodeA.textRectHeight+this.nodeA.textOffsetY;
return a};this.getEndPosition=function(){var a={x:this.nodeZ.getCx(),y:this.nodeZ.getCy()};a.y=this.nodeZ.y-8;return a};this.getPath=function(){var a=this.getStartPosition(),b=this.getEndPosition();if(this.nodeA===this.nodeZ)return[a,b];var c=[];c.push({x:a.x,y:a.y});c.push({x:a.x,y:b.y-32});c.push({x:b.x,y:b.y-32});c.push({x:b.x,y:b.y});return c};this.paintPath=function(a,b){a.beginPath();a.moveTo(b[0].x,b[0].y);null==this.dashedPattern&&(a.lineTo(b[1].x,b[1].y),this.roundLine?b[2].x<b[0].x?(a.lineTo(b[2].x+
5,b[2].y),a.moveTo(b[2].x,b[2].y+5),a.arc(b[2].x+5,b[2].y+5,5,1*Math.PI,1.5*Math.PI),a.moveTo(b[2].x,b[2].y+5)):b[2].x>b[0].x?(a.lineTo(b[2].x-5,b[2].y),a.arc(b[2].x-5,b[2].y+5,5,1.5*Math.PI,0),a.moveTo(b[2].x,b[2].y+5)):a.lineTo(b[2].x,b[2].y):a.lineTo(b[2].x,b[2].y),a.lineTo(b[3].x,b[3].y));a.stroke();a.closePath()}}d.prototype=new e.InteractiveElement;c.prototype=new d;e.Link=d;e.FlexionalLink=c})(JTopo);
(function(e){function d(c,b,e,w){b.x+=e;b.y+=w;b=a(c,b);for(var f=0;f<b.length;f++)d(c,b[f],e,w)}function c(c,b){function d(b,f){var h=a(c,b);null==e[f]&&(e[f]={},e[f].nodes=[],e[f].childs=[]);e[f].nodes.push(b);e[f].childs.push(h);for(var r=0;r<h.length;r++)d(h[r],f+1),h[r].parent=b}var e=[];d(b,0);return e}function a(a,b){for(var c=[],d=0;d<a.length;d++)a[d]instanceof e.Link&&a[d].nodeA===b&&c.push(a[d].nodeZ);return c}function h(a,b,c){if(a.layout){var d=a.layout,e=null,f=d.width||50,h=a.x,e=a.y+
a.height+61;a=b.length;var d=d.height||50,r=[];c=c?h-a/2*f+f/2:h;for(h=0;a>=h;h++)r.push({x:c+h*f,y:e+d});for(e=r;0>e[0].x;)for(c=0;c<e.length;++c)e[c].x+=f;20>e[0].x&&(e[0].x=20);for(f=0;f<b.length;f++)b[f].setLocation(e[f].x,e[f].y)}}function f(c,b,d){var e=a(c.childs,b);if(0==e.length)return null;h(b,e,d);6===e.length?f(c,e[0],!1):f(c,e[0],!0);return null}e.layout=e.Layout={layoutNode:f,adjustPosition:h,getNodeChilds:a,getTreeDeep:function(c,b){function d(b,c,g){c=a(b,c);g>e&&(e=g);for(var f=0;f<
c.length;f++)d(b,c[f],g+1)}var e=0;d(c,b,0);return e},getRootNodes:function(a){var b=[],c=a.filter(function(a){if(a instanceof e.Link)return!0;b.push(a);return!1});a=b.filter(function(a){for(var b=0;b<c.length;++b)if(c[b].nodeZ===a)return!1;return!0});return a=a.filter(function(a){for(var b=0;b<c.length;b++)if(c[b].nodeA===a)return!0;return!1})},TreeLayout:function(a,b){return function(f){function h(v,r){var m=e.layout.getTreeDeep(v,r),n=c(v,r),k=n[""+m].nodes,t=m*b;t+b>f.stage.canvas.height&&(f.stage.canvas.height=
t+b);for(var p=0;p<k.length;p++){var s=k[p],q=p*(a+10);s.setLocation(q,t)}for(p=m-1;0<=p;p--)for(m=n[""+p].nodes,v=n[""+p].childs,k=0;k<m.length;k++)if(s=m[k],q=v[k],s.y=0==p?0:p*b,0<q.length?s.x=(q[0].x+q[q.length-1].x)/2:0<k&&(s.x=m[k-1].x+m[k-1].width+54),0<k&&s.x<m[k-1].x+m[k-1].width+54)for(q=m[k-1].x+m[k-1].width+54,s=Math.abs(q-s.x),q=k;q<m.length;q++)d(f.childs,m[q],s,0)}var u=e.layout.getRootNodes(f.childs);if(0<u.length){h(f.childs,u[0]);var x=f.getCenterLocation().x-(u[0].x+u[0].width/
2);f.childs.forEach(function(a){a instanceof e.Node&&(a.x+=x,a.y+=5)})}}}}})(JTopo);
