#!/bin/sh /etc/rc.common
# Copyright (c) 2014, 2020 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# 2014 Qualcomm Atheros, Inc.
#
# All Rights Reserved.
# Qualcomm Atheros Confidential and Proprietary.

START=98

SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
    service_start /usr/sbin/thermald
}

stop() {
    service_stop /usr/sbin/thermald
}

restart() {
    stop
    start
}
